- hacking/cgroup_perf_recap_graph.py
Migrate `hacking/cgroup_perf_recap_graph.py` to this collection, since the `cgroup_perf_recap` callback lives here
hacking/cgroup_perf_recap_graph.py
```paste below
```
> Migrate hacking/cgroup_perf_recap_graph.py

- plugins/shell/csh.py
- plugins/shell/fish.py
Allow unsetting existing environment vars via environment by specifying a null value
This is related to https://github.com/ansible/ansible/pull/68236
shell plugins
N/A
> Allow unsetting env vars

- plugins/modules/acl.py
- plugins/modules/at.py
- plugins/modules/authorized_key.py
- plugins/modules/mount.py
- plugins/modules/patch.py
- plugins/modules/seboolean.py
- plugins/modules/selinux.py
- plugins/modules/synchronize.py
- plugins/modules/sysctl.py
Update EXAMPLES section in modules to use FQCN
plugins/modules/acl.py
plugins/modules/at.py
plugins/modules/mount.py
plugins/modules/patch.py
plugins/modules/seboolean.py
plugins/modules/selinux.py
plugins/modules/sysctl.py
> Update EXAMPLES section in modules

- plugins/modules/acl.py
- plugins/modules/at.py
- plugins/modules/authorized_key.py
- plugins/modules/mount.py
- plugins/modules/patch.py
- plugins/modules/seboolean.py
- plugins/modules/selinux.py
- plugins/modules/synchronize.py
- plugins/modules/sysctl.py
plugins/modules/acl.py
plugins/modules/at.py
plugins/modules/mount.py
plugins/modules/patch.py
plugins/modules/seboolean.py
plugins/modules/selinux.py
plugins/modules/sysctl.py
> Remove Ansible metadata from modules

- tests/integration/targets/at/aliases
- tests/integration/targets/at/tasks/main.yml
- tests/integration/targets/patch/aliases
- tests/integration/targets/patch/tasks/main.yml
- tests/integration/targets/synchronize/aliases
- tests/integration/targets/synchronize/tasks/main.yml
Reverts ansible-collections/ansible.posix#5
Fixes #3
> Revert "Enable at, patch and synchronize tests"

- galaxy.yml
Signed-off-by: Paul Belanger <pabelanger@redhat.com>
> Remove license key from galaxy.yml

- galaxy.yml
Signed-off-by: Paul Belanger <pabelanger@redhat.com>
> Prepare for 0.1.3 release

- README.md
Attempting to get the Ansible-maintained READMEs to be more alike.
docs
```paste below
```
> update readme with contributor guide link etc

- .gitignore
- changelogs/config.yaml
- changelogs/fragments/12_migrate_cgroup_perf_recap_graph.yml
- changelogs/fragments/14_mount_option.yml
- changelogs/fragments/15_profile_tasks.yml
- changelogs/fragments/19_enable_tags.yml
- changelogs/fragments/25_ansible_metadata.yml
- changelogs/fragments/26_profile_tasks_doc.yml
- changelogs/fragments/27_update_examples.yml
- changelogs/fragments/33_mount.yml
- changelogs/fragments/35_disable_tests.yml
- changelogs/fragments/39_remove_license.yml
- changelogs/fragments/43_remove_shippable.yml
- changelogs/fragments/4_update_readme.yml
- changelogs/fragments/5_enable_tests.yml
- changelogs/fragments/6_test_devel.yml
- changelogs/fragments/7_env.yml
- changelogs/fragments/initial_commit.yaml
* Added missing changelog entries
* Updated configuration for changelog generation
.gitignore
changelogs/config.yaml
changelogs/fragments/12_migrate_cgroup_perf_recap_graph.yml
changelogs/fragments/14_mount_option.yml
changelogs/fragments/15_profile_tasks.yml
changelogs/fragments/19_enable_tags.yml
changelogs/fragments/25_ansible_metadata.yml
changelogs/fragments/26_profile_tasks_doc.yml
changelogs/fragments/27_update_examples.yml
changelogs/fragments/33_mount.yml
changelogs/fragments/35_disable_tests.yml
changelogs/fragments/39_remove_license.yml
changelogs/fragments/43_remove_shippable.yml
changelogs/fragments/4_update_readme.yml
changelogs/fragments/5_enable_tests.yml
changelogs/fragments/6_test_devel.yml …
> Update changelog generation configuration

- plugins/modules/authorized_key.py
Handle OSError raised due to permission issue while
creating directory.
Fixes: ansible/ansible#34001
> authorized_key: Handle OSError raised

- changelogs/config.yaml
> Fix changelog config

- changelogs/fragments/11-action-plugins-use-fqcn.yml
- plugins/action/patch.py
- plugins/action/synchronize.py
use FQCN for module call in action plugins
Fixes https://github.com/ansible-collections/ansible.posix/issues/11
ansible.posix.patch
ansible.posix.synchronize
> use FQCN for module call in action plugins

- README.md
- docs/ansible.posix.acl_module.rst
- docs/ansible.posix.at_module.rst
- docs/ansible.posix.authorized_key_module.rst
- docs/ansible.posix.mount_module.rst
- docs/ansible.posix.patch_module.rst
- docs/ansible.posix.seboolean_module.rst
- docs/ansible.posix.selinux_module.rst
- docs/ansible.posix.synchronize_module.rst
- docs/ansible.posix.sysctl_module.rst
- galaxy.yml
- meta/runtime.yml
- plugins/modules/acl.py
- plugins/modules/at.py
- plugins/modules/authorized_key.py
- plugins/modules/mount.py
- plugins/modules/patch.py
- plugins/modules/seboolean.py
- plugins/modules/selinux.py
- plugins/modules/synchronize.py
- plugins/modules/sysctl.py
Content Collection 1.0.0 Release
ansible.posix
> Content Collection 1.0.0 Release

- plugins/modules/patch.py
- tests/integration/targets/patch/files/result_whitespace.patch
- tests/integration/targets/patch/tasks/main.yml
Add the option to ignore whitespace changes between patch and input.
patch
> patch - add option to ignore whitespace changes

- changelogs/fragments/firewalld_migration.yml
- plugins/module_utils/firewalld.py
- plugins/modules/firewalld.py
- tests/integration/targets/firewalld/aliases
- tests/integration/targets/firewalld/meta/main.yml
- tests/integration/targets/firewalld/tasks/main.yml
- tests/integration/targets/firewalld/tasks/port_test_cases.yml
- tests/integration/targets/firewalld/tasks/run_all_tests.yml
- tests/integration/targets/firewalld/tasks/service_test_cases.yml
- tests/integration/targets/firewalld/tasks/source_test_cases.yml
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.9.txt
migrate firewalld from community.general
- New Module Pull Request
firewalld
> migrate firewalld from community.general

- README.md
- docs/ansible.posix.firewalld_module.rst
- docs/ansible.posix.patch_module.rst
- galaxy.yml
Docs and metadata prep for 1.1.0 release to include firewalld module
ansible.posix
> Prep Collection for 1.1.0 release

- README.md
fix broken docs links pointing to old primary branch
ansible.posix
> fix broken docs links pointing to old primary branch

- tests/utils/shippable/shippable.sh
Fixes #73
https://github.com/ansible-collections/ansible.posix/issues/73
ansible.posix
> don't run coverage analyze on Ansible 2.9

- changelogs/fragments/skippy_deprecation.yml
- plugins/callback/skippy.py
Fixes https://github.com/ansible-collections/ansible.posix/issues/62
skippy
> fix skippy callback deprecation warning

- CHANGELOG.rst
- changelogs/changelog.yaml
- docs/ansible.posix.acl_module.rst
- docs/ansible.posix.at_module.rst
- docs/ansible.posix.authorized_key_module.rst
- docs/ansible.posix.firewalld_module.rst
- docs/ansible.posix.mount_module.rst
- docs/ansible.posix.patch_module.rst
- docs/ansible.posix.seboolean_module.rst
- docs/ansible.posix.selinux_module.rst
- docs/ansible.posix.synchronize_module.rst
- docs/ansible.posix.sysctl_module.rst
- galaxy.yml
Run add_docs.py
Run antsibull-changelog; backfill for prior releases
Bump release in galaxy.yml
Add .keep to changelogs/fragments so directory is not deleted if
`keep_fragments` is ever set to False.
ansible.posix
> Prepare 1.1.1 release

- changelogs/fragments/101-sysctl-dont-persist-when-invalid.yml
add changelog fragment for PR#101
sysctl
> add changelog fragment for PR#101

- plugins/modules/synchronize.py
Fix the documentation indentation
synchronize
use the correct YAML indentation in the doc
> fix indentation in doc

- .azure-pipelines/README.md
- .azure-pipelines/azure-pipelines.yml
- .azure-pipelines/scripts/aggregate-coverage.sh
- .azure-pipelines/scripts/combine-coverage.py
- .azure-pipelines/scripts/process-results.sh
- .azure-pipelines/scripts/publish-codecov.sh
- .azure-pipelines/scripts/report-coverage.sh
- .azure-pipelines/scripts/run-tests.sh
- .azure-pipelines/scripts/time-command.py
- .azure-pipelines/templates/coverage.yml
- .azure-pipelines/templates/matrix.yml
- .azure-pipelines/templates/test.yml
- tests/utils/shippable/shippable.sh
Initial AZP configuration.
Will not run at this stage.
> Initial Azure Pipeline config

- README.md
> AZP Badge for README.md

- .azure-pipelines/scripts/report-coverage.sh
> AZP: Install ansible-test for coverage

- .azure-pipelines/azure-pipelines.yml
- tests/utils/shippable/macos.sh
.azure-pipelines/azure-pipelines.yml
> Update OS as per guidelines

- .azure-pipelines/azure-pipelines.yml
- .azure-pipelines/scripts/aggregate-coverage.sh
- .azure-pipelines/scripts/report-coverage.sh
- README.md
https://github.com/ansible-collections/overview/issues/45#issuecomment-776859063
`.azure-pipelines/azure-pipelines.yml`
> Update azure-pipelines.yml and README.md

- changelogs/fragments/118-synchronize_bugfix.yml
- changelogs/fragments/120-synchronize_add_option.yml
- changelogs/fragments/99-at_add_aix_support.yml
Add fragments for:
https://github.com/ansible-collections/ansible.posix/pull/120
https://github.com/ansible-collections/ansible.posix/pull/118
https://github.com/ansible-collections/ansible.posix/pull/99
> Add missed changelog fragments

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1.2.0.yml
- changelogs/fragments/101-sysctl-dont-persist-when-invalid.yml
- changelogs/fragments/82-private-key-override-fix.yml
- changelogs/fragments/firewalld_zone_target.yml
- galaxy.yml
> Release 1.2.0 commit

- .azure-pipelines/azure-pipelines.yml
Updated `.azure-pipelines/azure-pipelines.yml` to use the latest Azure Pipeline Test Container Image v1.9.0.
- Azure Pipeline.
> Updated Azure Pipeline Test Container Image URL to use v1.9.0

- .azure-pipelines/azure-pipelines.yml
- changelogs/fragments/test_matrix.yml
- tests/sanity/ignore-2.12.txt
Depends-On: https://github.com/ansible/project-config/pull/772
Add 2.11 branch to test matrix, add ignore-2.12.txt
https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100
> Add 2.11 branch to test matrix, add ignore-2.12.txt

- .azure-pipelines/scripts/publish-codecov.sh
- changelogs/fragments/181-update_codecov_sh_url.yml
- tests/utils/shippable/shippable.sh
https://github.com/ansible-collections/overview/issues/45#issuecomment-829350163
> Update codecov.sh URL

- changelogs/fragments/207-mount_tests.yml
- tests/integration/targets/mount/tasks/main.yml
mount integration tests: make them more human readable
`tests/integration/targets/mount/tasks/main.yml`
> mount integration tests: make them more human readable

- changelogs/fragments/126_mount_not_returning_backup_file.yml
- plugins/modules/mount.py
- tests/integration/targets/mount/tasks/main.yml
Resolves Merge conflict in #128 which Fixes #126 
mount
```paste below
Conflicting files in #128 
tests/integration/targets/mount/tasks/main.yml
```
> Fix: Resolve merge conflict - mount return backup_file(#128)

- README.md
Update README.md with ansible versions and release notes:
* Update ansible-core versions in the Tested with ansible section.
* Change the Release notes section to use CHANGELOG.rst link.
None
> Update README.md with ansible versions and release notes

- changelogs/fragments/firewalld_integ_test.yml
- tests/integration/targets/firewalld/tasks/main.yml
> Fix integration test fedora 34 with firewalld

- changelogs/fragments/firewalld_integ_test.yml
Changed from `bugfixes` to `trivial`
changelogs/fragments/firewalld_integ_test.yml
> fix changelog entry

- changelogs/fragments/sanity_fixes.yml
- tests/sanity/ignore-2.12.txt
- tests/unit/mock/loader.py
changelogs/fragments/sanity_fixes.yml
tests/sanity/ignore-2.12.txt
tests/unit/mock/loader.py
> sanity fixes for pylint test

- galaxy.yml
Modify the version number to prepare next release.
* 1.3.0 => 1.4.0
None
> Modify version number to prepare next release 1.4.0

- changelogs/fragments/272-copy_ignore_txt.yml
- tests/sanity/ignore-2.13.txt
Relates to https://github.com/ansible-collections/overview/issues/45#issuecomment-926794724
> Copy ignore-2.12.txt to ignore-2.13.txt

- codecov.yml
> Codecov comment=false

- .azure-pipelines/azure-pipelines.yml
Add CI tests for Ansible Core 2.12
- Fixes #290 
- ansible.posix/.azure-pipelines/azure-pipelines.yml
None
> [CI] Add CI tests for Ansible Core 2.12 release

- README.md
Fixed the tested version list in `Tested with Ansible` section.
- Fixes #290
aisnbie.posix/README.md
None
> [docs] Fixed the tested version list in Tested with Ansible section

- .azure-pipelines/azure-pipelines.yml
Replace RHEL8.4 with RHEL8.5 for devel tests
- https://github.com/ansible-collections/overview/issues/45#issuecomment-970959091
- azure-pipelines/azure-pipelines.yml
None
> [CI] Replace RHEL8.4 with RHEL8.5 for devel tests

- .azure-pipelines/azure-pipelines.yml
Update AZP config:
* Fixes ansible-collections/overview#45
* Fixes #308
```paste below
None
```
> [CI] Update AZP matrix for ansible devel branch

- changelogs/fragments/346_copy_ignore_txt_for_devel.yml
- tests/sanity/ignore-2.14.txt
As a part of issue #345, it addresses CI tests for devel(2.14.0.dev0).
- CT tests Pull Request
None
> Copy ignore-2.13.txt to ignore-2.14.txt

- README.md
- changelogs/fragments/349_follow_new_guidelines.yml
- meta/runtime.yml
- plugins/callback/cgroup_perf_recap.py
- plugins/callback/debug.py
- plugins/callback/json.py
- plugins/callback/profile_roles.py
- plugins/callback/profile_tasks.py
- plugins/callback/skippy.py
- plugins/callback/timer.py
- plugins/modules/mount.py
- plugins/shell/csh.py
- plugins/shell/fish.py
Fixed documentation and options to address new sanity tests:
- Addresses #348 
- https://docs.ansible.com/ansible/latest/dev_guide/testing_validate-modules.html
None
> [CI] Fixed documentation and options to address new sanity tests

- bindep.txt
Add RHEL9 build for rsync.
bindep.txt
>  Update bindep.txt for adding rhel-9

- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- changelogs/fragments/211_fstab_append_newline.yml
- changelogs/fragments/247_firewalld.yml
- changelogs/fragments/254_variable_warnings.yml
- changelogs/fragments/255_authorized_key_url.yml
- changelogs/fragments/263_profile_tasks_with_serial.yml
- changelogs/fragments/272-copy_ignore_txt.yml
- changelogs/fragments/277_fix_integration_test_on_devel.yml
- changelogs/fragments/282_fix_unit_test_for_synchronize.yml
- changelogs/fragments/287_firewalld_requirements.yml
- changelogs/fragments/288_mounts_options.yml
- changelogs/fragments/297_firewalld_exclusive_options_handling.yml
- changelogs/fragments/299_seboolean_python3.yml
- changelogs/fragments/302_shippable_exit_code.yml
- changelogs/fragments/304_pep632.yml
- changelogs/fragments/346_copy_ignore_txt_for_devel.yml
- changelogs/fragments/347_add_branch_213.yml
- changelogs/fragments/349_follow_new_guidelines.yml
- changelogs/fragments/353_ci_fix_unittest_for_synchronize.yml
- changelogs/fragments/disable_selinux_via_kernel_cmdline.yml
- changelogs/fragments/psf-license.yml
- changelogs/fragments/sanity_fixes.yml
- changelogs/fragments/shell_escape_full_path_for_rsync.yml
- docs/ansible.posix.authorized_key_module.rst
- docs/ansible.posix.firewalld_module.rst
- docs/ansible.posix.mount_module.rst
- docs/ansible.posix.seboolean_module.rst
- docs/ansible.posix.selinux_module.rst
Release 1.4.0 commit
```paste below
None
```
> Release 1.4.0 commit

- changelogs/fragments/366_update_version_number_for_galaxy.yml
- galaxy.yml
Update version number in galaxy.yml to 1.5.0.
None
> Update version number in galaxy.yml to 1.5.0.

- .azure-pipelines/azure-pipelines.yml
- changelogs/fragments/371_refactoring_ci_process_202206.yml
- tests/utils/shippable/shippable.sh
Refactored AZP settings and CI script to correct the following PR's side effects:
* Addresses https://github.com/ansible-collections/ansible.posix/pull/369
None
> [CI] Refactor AZP settings and CI script

- .azure-pipelines/azure-pipelines.yml
- changelogs/fragments/389_ci_add_stable_214.yml
- tests/sanity/ignore-2.15.txt
Add stable-2.14 branch to Azure pipleline.
* Fixes #388
Relates to https://github.com/ansible-collections/news-for-maintainers/issues/24
```
None
```
> Add stable-2.14 branch to AZP

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/166_mount_absent_fstab.yml
- changelogs/fragments/267_mount_ephemeral.yml
- changelogs/fragments/366_update_version_number_for_galaxy.yml
- changelogs/fragments/371_refactoring_ci_process_202206.yml
- changelogs/fragments/373_firewall_fix_missing_library_message.yml
- changelogs/fragments/375_update_azp_container.yml
- changelogs/fragments/380_update_usage_profile_tasks.yml
- changelogs/fragments/386_follow_ci_testing_rules.yml
- changelogs/fragments/389_ci_add_stable_214.yml
- changelogs/fragments/390_hosts_involved_same_password.yml
- changelogs/fragments/393-rpm-ostree.yml
- changelogs/fragments/393_rhel_for_edge.yml
- changelogs/fragments/400-fix-boolean-values-in-docs.yml
- changelogs/fragments/401_document_module_default_values.yml
- changelogs/fragments/407_fix_firewalld_port_test.yml
- changelogs/fragments/409_update_azp_matrix.yml
> v1.5.1 changelog

- changelogs/fragments/425-support_test-sanity-docker-devel.yml
- plugins/module_utils/version.py
- plugins/modules/firewalld_info.py
- tests/unit/compat/builtins.py
- tests/unit/plugins/action/test_synchronize.py
Support new test-sanity-docker-devel test.
- CI test Pull Request
- New test-sanity-docker-devel test is currently non-voting state.
> Support new test-sanity-docker-devel test 

- changelogs/fragments/535-add-jsonl-callback.yml
- plugins/callback/jsonl.py
New `jsonl` callback plugin writes log in JSONL format - one JSON line for each event (callback function call).
Fixes #436
- New Module Pull Request
ansible.posix.jsonl
> Add jsonl callback plugin to ansible.posix collection

- .azure-pipelines/azure-pipelines.yml
- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- changelogs/fragments/399_firewalld_create_remove_zone_when_offline.yml
- changelogs/fragments/413-synchronize-seealso.yml
- changelogs/fragments/417-add-protocol-parameter.yml
- changelogs/fragments/419-fix-patch-doc.yml
- changelogs/fragments/425-support_test-sanity-docker-devel.yml
- changelogs/fragments/426-firewalld_info-doc-update.yml
- changelogs/fragments/434-fix-rhel_facts-exit_json.yml
- changelogs/fragments/535-add-jsonl-callback.yml
- docs/ansible.posix.acl_module.rst
- docs/ansible.posix.at_module.rst
- docs/ansible.posix.authorized_key_module.rst
- docs/ansible.posix.firewalld_info_module.rst
- docs/ansible.posix.firewalld_module.rst
- docs/ansible.posix.mount_module.rst
- docs/ansible.posix.patch_module.rst
- docs/ansible.posix.rhel_facts_module.rst
- docs/ansible.posix.rhel_rpm_ostree_module.rst
- docs/ansible.posix.rpm_ostree_upgrade_module.rst
- docs/ansible.posix.seboolean_module.rst
- docs/ansible.posix.synchronize_module.rst
- docs/ansible.posix.sysctl_module.rst
- galaxy.yml
Release 1.5.2 commit
- https://github.com/ansible-collections/ansible.posix/issues/149#issuecomment-1499798028
```paste below
None
```
> Release 1.5.2 commit

- galaxy.yml
Bump release version in galaxy.yml for the next release
```paste below
None
```
> Bump release version in galaxy.yml for the next release

- .azure-pipelines/azure-pipelines.yml
- changelogs/fragments/445_ci_support_stable-215.yml
- tests/utils/shippable/shippable.sh
Update AZP to support stable-2.15 branch.
- Fixes #444 
```paste below
None
```
> Update AZP to support stable-2.15 branch

- changelogs/fragments/448_support_new_sanity_test.yml
- tests/sanity/ignore-2.16.txt
Support sanity docker test on devel(2.16.0.dev0) branch:
- Fixes #446
```paste below
None
```
> [CI] Support sanity docker test on devel(2.16.0.dev0) branch

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/343-fix-profile_tasks-callback-documentation.yml
- changelogs/fragments/402_firewall_fix_offline_interface_add.yml
- changelogs/fragments/404_firewalld_masquerade_icmp_block_inversion_bugfixes.yml
- changelogs/fragments/440-json-add-path-field.yaml
- changelogs/fragments/441-json-add-indent-parameter.yaml
- changelogs/fragments/445_ci_support_stable-215.yml
- changelogs/fragments/448_support_new_sanity_test.yml
- changelogs/fragments/451_firewall_fix_protocol_parameter.yml
- changelogs/fragments/456_sysctl_fix_nonetype.yml
- galaxy.yml
> Release 1.5.4

- .azure-pipelines/azure-pipelines.yml
- changelogs/fragments/477_ci_update.yml
- tests/utils/shippable/shippable.sh
Replace Python3.9 with 3.12 for ansible-test
- Addresses issue #476
- CI Test Pull Request
```paste below
None
```
> Update CI tests to address changes on ansible-core

- .azure-pipelines/azure-pipelines.yml
Change to the CI system annnounced in the following required this change:
https://github.com/ansible-collections/news-for-maintainers/issues/47
> Update azure-pipelines for new RHEL versions

- tests/unit/compat/mock.py
Replaced yield with yield from to address latest sanity test.
None
> [CI] Replaced yield with yield from for sanity test

- plugins/modules/acl.py
- plugins/modules/at.py
- plugins/modules/authorized_key.py
- plugins/modules/firewalld.py
- plugins/modules/firewalld_info.py
- plugins/modules/mount.py
- plugins/modules/patch.py
- plugins/modules/rhel_facts.py
- plugins/modules/rhel_rpm_ostree.py
- plugins/modules/seboolean.py
- plugins/modules/selinux.py
- plugins/modules/synchronize.py
- plugins/modules/sysctl.py
Review the doc blocks of the modules in the collection.
plugins/modules/acl.py
plugins/modules/at.py
plugins/modules/firewalld_info.py
plugins/modules/mount.py
plugins/modules/patch.py
plugins/modules/rhel_facts.py
plugins/modules/rhel_rpm_ostree.py
plugins/modules/seboolean.py
plugins/modules/selinux.py
plugins/modules/sysctl.py
> review modules docs

- changelogs/fragments/566_bump_version_161.yml
- galaxy.yml
* Bump version to 1.6.1 to prepare the next release
* Update document site link
ansible.posix
```paste below
None
```
> Bump version to 1.6.1 to prepare the next release

- changelogs/fragments/581_ci_selinux.yml
- tests/integration/targets/selinux/tasks/selinux.yml
Conditions for selinux integration tests have been modified to be more accurate.
This fix only affects integration tests, so it will not affect module behavior.
* ansible.posix.selinux
None
> [CI] Modify conditions for selinux integratuion tests

- README.md
- changelogs/fragments/587_update_README.yml
This PR updates README.md to cover [Red Hat guidelines](https://access.redhat.com/articles/7068606)
Also, this new content aligns with the [community template](https://github.com/ansible-collections/collection_template/blob/main/README.md) content guidelines.
* Fixes #585
```paste below
None
```
> Update README to cover RH guidelines

- .azure-pipelines/azure-pipelines.yml
- README.md
- changelogs/fragments/588_ci_enable_devel.yml
Enabled integration tests for `devel` branch
- Remote tests
- Docker tests
```paste below
None
```
> [CI] enabled integration tests for devel branch

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/365-boot-linux.yml
- changelogs/fragments/387_callback_output_header.yml
- changelogs/fragments/566_bump_version_161.yml
- changelogs/fragments/567_remove_version_added.yml
- changelogs/fragments/568_update_authorized_key.yml
- changelogs/fragments/570_nfs4_acl.yml
- changelogs/fragments/571_ci_bump_core_version.yml
- changelogs/fragments/576_bump_version_2.yml
- changelogs/fragments/581_ci_selinux.yml
- changelogs/fragments/584_firewalld_opt_type.yml
- changelogs/fragments/587_update_README.yml
- changelogs/fragments/588_ci_enable_devel.yml
- changelogs/fragments/593_replace_freebsd_version.yml
- changelogs/fragments/597_remove_fstab_comment_on_updating.yml
- changelogs/fragments/598_icmp_block_inversion.yml
Release 2.0.0 commit
- Release Plan https://github.com/ansible-collections/ansible.posix/issues/149
Feature Pull Request
ansible.posix
This will be merged on 5 December if there are no problems
> Release 2.0.0 commit

- changelogs/fragments/603_bump_version_3.yml
- galaxy.yml
Bump version to 3.0.0 for the next release on main branch:
* Fixes #603
```paste below
None
```
> Bump version to 3.0.0 for the next release

- .azure-pipelines/azure-pipelines.yml
- tests/utils/shippable/shippable.sh
Signed-off-by: Abhijeet Kasurde <Akasurde@redhat.com>
> [CI] update test containers

- .azure-pipelines/azure-pipelines.yml
- changelogs/fragments/618_ci_remove_ubuntu2004.yml
Remove ubuntu20.04 from CI tests
* Fixes #612
* ansible.posix
```paste below
None
```
> [AZP] Remove ubuntu20.04 from CI tests

- .azure-pipelines/azure-pipelines.yml
Update CI test environment to remove Ubuntu 20.04
* Addresses #612
```paste below
None
```
> [AZP][stable-1] Update CI test environment

- .azure-pipelines/azure-pipelines.yml
[AZP][stable-2] Update CI test environment
- Addresses #612
```paste below
None
```
> [AZP][stable-2] Update CI test environment

- tests/integration/targets/mount/tasks/main.yml
* added check mode tests (assert no changes made)
* added comments to make file less scary
tests
`mount`
> improve mount integration tests

- changelogs/fragments/631_fixes_module_path.yml
- plugins/callback/cgroup_perf_recap.py
- tests/integration/targets/seboolean/tasks/main.yml
- tests/integration/targets/selinux/tasks/main.yml
Fixes a bug related to updating the ansible-core devel branch.
* Fixes incorrect load path for `json` module in cgroup_perf_recap
* Remove unnecessary condition from seboolean integration tests
* Optimize conditions for selinux integration tests
* Fixes #630
- ansible.posix.cgroup_perf_recap
```
N/A
```
> Fixes issue related to latest ansible-core devel branch

- changelogs/fragments/631_fixes_module_path.yml
- plugins/callback/cgroup_perf_recap.py
- tests/integration/targets/seboolean/tasks/main.yml
- tests/integration/targets/selinux/tasks/main.yml
Fixes a bug related to updating the ansible-core devel branch.
- Fixes incorrect load path for json module in cgroup_perf_recap
- Remove unnecessary condition from seboolean integration tests
- Optimize conditions for selinux integration tests
- Fixes #630
Bugfix Pull Request
ansible.posix.cgroup_perf_recap
N/A
>  [stable-1] Backport: #631

- .azure-pipelines/azure-pipelines.yml
- changelogs/fragments/642_ci_add_rhel10.yml
- tests/integration/targets/acl/tasks/acl.yml
Update AZP CI Matrix.
* Fixes #642
* Backport #640 
* Backport #646
* CI tests
* ansible.posix
```
N/A
```
> [Backport][stable-2][AZP] Update CI Matrix

- README.md
- changelogs/fragments/665_update_readme_20250728.yml
README updated with the release of Ansible Core 2.19
* https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_19.html
```paste below
N/A
```
> Update README for release of Ansible Core 2.19

- .azure-pipelines/azure-pipelines.yml
- changelogs/fragments/666_azp_update_20250728.yml
- tests/integration/targets/firewalld/aliases
Update AZP matrix to follow ansible-test changes:
- #666 
```
None
```
> [Backport][stable-2] #666

- README.md
- changelogs/fragments/665_update_readme_20250728.yml
Update the README with the release of Ansible Core 2.19
- #665 
```
N/A
```
> [Backport][stable-2] #665
