ansible-collections/ansible.posix

tests/integration/targets/at/aliases
tests/integration/targets/at/tasks/main.yml
tests/integration/targets/patch/aliases
tests/integration/targets/patch/tasks/main.yml
tests/integration/targets/synchronize/aliases
tests/integration/targets/synchronize/tasks/main.yml

Updates tests to either skip completely when `ansible_pkg_mgr` isn't one of the base package managers, or just skip `package` tasks in the same scenario.
`at` isn't universally installed it seems, so that one is skipped completed on unsupported targets.
See https://github.com/ansible-collections/ansible.posix/issues/3
```paste below
```

Enable at, patch and synchronize tests

---

plugins/callback/profile_tasks.py

Fix issue ansible/ansible#59059
When no sorting was selected, `result` was a `odict_items` which is not subscriptable, so the slicing was failing.
profile_tasks
Before:
```shell
export ANSIBLE_CALLBACK_WHITELIST=ansible.posix.profile_tasks
export PROFILE_TASKS_SORT_ORDER=none
ansible-playbook playbook.yml  # with any playbook, a simple one doing a ping is enough
[WARNING]: Failure using method (v2_playbook_on_stats) in callback plugin (<ansible_collections.ansible.posix.plugins.callback.profile_tasks.CallbackModule object at 0x7fa51ef37d90>): 'odict_items' object is not subscriptable
```
After:
```shell
export ANSIBLE_CALLBACK_WHITELIST=ansible.posix.profile_tasks
export PROFILE_TASKS_SORT_ORDER=none
ansible-playbook playbook.yml
Gathering Facts …
```

Fix issue ansible/ansible#59059

---

plugins/modules/mount.py
tests/integration/targets/mount/tasks/main.yml

Goal: Handle remount with new options.  This ensures that people can use the ansible version of `mount -o remount,exec /tmp` as expected for temporary changed in the mounting options without changing the `fstab`.
Fixes ansible/ansible#59460
mount
Without change:
```
remote $ grep ' /tmp' /etc/fstab
/dev/mapper/vg_workstation-lv_tmp /tmp ext4 nosuid,nodev,noexec,defaults        0       2
remote $ mount | grep /tmp
/dev/mapper/vg_workstation-lv_tmp on /tmp type ext4 (rw,nosuid,nodev,noexec,relatime,data=ordered)
controller $ ansible all -i "[REDACTED]," -m mount -a 'path=/tmp state=remounted opts=exec' --user [REDACTED] --ask-pass --become --ask-become-pass --become-user root
[REDACTED] | CHANGED => {
"ansible_facts": { …
```

Copy and adjust changes from ansible/ansible#59530

---

plugins/callback/profile_tasks.py

If user specifies sort_order to none, results are not converted to list.
This fix force this typecasting before using the results.
Fixes: https://github.com/ansible/ansible/issues/69563
plugins/callback/profile_tasks.py

Typecast results before use in profile_tasks callback

---

plugins/modules/mount.py
tests/integration/targets/mount/aliases
tests/unit/modules/system/test_mount.py

Partially revert "mount: Check if src exists before mounted (ansible/ansible#61752)"
This reverts part of ansible commit 72023d7462e78635264fd12bfdb23894b4163cba.
The immediate reason is that it breaks mounts where src is not a path.
Examples of such mounts are network-based filesystems such as nfs, cifs,
glusterfs, ceph, virtual filesystems such as tmpfs or overlayfs, and
also UUID-based mounts. It is too hard to come with an exhaustive list,
especially if we take non-Linux systems into account, so don't even try.
Additionally, it did not really fix the issue (ansible/ansible#59183) that
it intended to fix, because the mount could fail but leave a non-working
fstab entry for reasons other than non-existing src path.
Restore fstab and remove the mount point after a failed mount
Add a …

revert "mount: Check if src exists before mounted (ansible/ansible#61752)"

---

galaxy.yml

We need to do this manually, as some tests are still in shippable.
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

Bump version to 0.1.2

---

changelogs/.gitignore
changelogs/fragments/23-selinux-doesnt-create-missing-config-keys
plugins/modules/selinux.py
tests/integration/targets/selinux/tasks/selinux.yml

Previously the selinux module would only edit the state of found
configuration keys SELINUX and SELINUXTYPE in /etc/selinux/config but
would not add them with desired state if they were not found.
Fixes #23
https://github.com/ansible-collections/ansible.posix/issues/23
selinux

selinux - add missing config keys when needed

---

changelogs/fragments/17_authorized_keys.yml
plugins/modules/authorized_key.py

Last try had a space at the end for some weird reason.

Updates authorized_key.py to be used with FIDO2 security keys.

---

changelogs/fragments/65931-json-callback-non-lockstep-output.yml
plugins/callback/json.py

Fix json callback for non-lockstep strategy plugins such as free. Fixes #65931
lib/ansible/plugins/callback/json.py
```paste below
```

Fix json callback for non-lockstep strategy plugins such as free

---

changelogs/fragments/37-authorized_keys-inconsistent-check-mode-values.yml
plugins/modules/authorized_key.py
tests/integration/targets/authorized_key/tasks/main.yml

Previously check_mode would incorrectly return changed=False even when a
change would have taken place if ran without check_mode, with
integration tests that confirmed this incorrect behavior. Also the
module did not correctly populate the return values when run in
check_mode. Both of these issues are resolved in this PR.
Fixes https://github.com/ansible-collections/ansible.posix/issues/37
ansible.posix.authorized_keys

authorized_keys - consistent behavior in check_mode

---

README.md
docs/ansible.posix.patch_module.rst
galaxy.yml
plugins/modules/patch.py

remove references to old default branch name
ansible.posix
```

remove references to old default branch name

---

shippable.yml

disable AIX tests in shippable for now because of intermittent failures from IBM Cloud
ansible.posix

disable AIX tests in shippable for now because of intermittent failures from IBM Cloud

---

changelogs/fragments/74_synchronize_docker.yml
plugins/action/synchronize.py

Adds the new collection-namespaced names for `docker` and `buildah` connection plugins to the conditionals in the `synchronize` action plugin.
`synchronize` action plugin
With certain connection plugins moved into collections, the `docker` and `buildah` connections are redirected to  `ansible.community.docker` and `containers.podman.buildah`, respectively. Since the `synchronize` action plugin is explicitly checking for `docker` and `buildah`, it fails to work as-is with the updated connection names. e.g:
```
fatal: [docker_host]: FAILED! => {"changed": false, "msg": "synchronize uses rsync to function. rsync needs to connect to the remote host via ssh, docker client or a direct filesystem copy. This remote host is being accessed via community.general.docker instead …
```

Fix synchronize to work with renamed docker and buildah connection plugins.

---

plugins/modules/firewalld.py

Add a link for Firewalld Rich Rules for further documentation.

firewalld: Add a Link for rich rules

---

tests/sanity/ignore-2.10.txt
tests/utils/shippable/shippable.sh

Remove no longer necessary ignore
Fix shippable.sh to use correct ansible_version variable and don't
quote pattern to be matched by =~
tests/utils/shippable/shippable.sh
tests/sanity/ignore-2.10.txt

Fix sanity test failures

---

plugins/modules/synchronize.py

This option has interactions with `ansible_ssh_common_args` as indicated in this issue thread: https://github.com/ansible/ansible/issues/16767
- New Module Pull Request
```paste below
```

Updated description of `use_ssh_args` option for synchronize.py

---

changelogs/fragments/82-private-key-override-fix.yml
plugins/action/synchronize.py
tests/unit/plugins/action/fixtures/synchronize/basic_with_private_key/meta.yaml
tests/unit/plugins/action/fixtures/synchronize/basic_with_private_key/taskvars_in.json
tests/unit/plugins/action/fixtures/synchronize/basic_with_private_key/taskvars_out.json
tests/unit/plugins/action/fixtures/synchronize/delegate_remote_play_context_private_key/meta.yaml
tests/unit/plugins/action/fixtures/synchronize/delegate_remote_play_context_private_key/task_vars_in.json
tests/unit/plugins/action/fixtures/synchronize/delegate_remote_play_context_private_key/task_vars_out.json
tests/unit/plugins/action/fixtures/synchronize/delegate_remote_with_private_key/meta.yaml
tests/unit/plugins/action/fixtures/synchronize/delegate_remote_with_private_key/task_vars_in.json
tests/unit/plugins/action/fixtures/synchronize/delegate_remote_with_private_key/task_vars_out.json
tests/unit/plugins/action/test_synchronize.py

The private_key parameter of synchronize module task gets overridden by the playbook --private-key variable path.
This PR is used to fix this. 
synchronize
```
cat play.yml
- hosts: agents
remote_user: vbm
tasks:
- name: Fetching the /etc/hosts from manager to agent nodes
synchronize:
src:  "/etc/hosts"
dest: "/home/vbm/"
private_key: "/home/vbm/test.pem"
delegate_to: "{{item}}"
with_items: "{{groups['manager']}}"
```
```
ansible-playbook --private-key=/home/vbm/access.pem -i inventory play.yml -vvv
```
```	  
failed: [10.75.180.184 -> 10.75.180.139] (item=10.75.180.139) => {
"ansible_loop_var": "item",
"changed": false,
"cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -i /home/vbm/access.pem -o StrictHostKeyChecking=no -o …
```

Fix for private_key overriding in synchronize module

---

plugins/modules/at.py

The `at` module does not work correctly on AIX.
Trying to remove a job fails with a syntax error.
Setting the `unique` attribute to `yes` also fails.
AIX uses `-lv` options to cat a job (instead of `-c` for Linux) and `-r` to remove a job.
Linux supports both `-r` and `-d`, so use `-r` since it is what POSIX says.
See https://www.ibm.com/support/knowledgecenter/ssw_aix_72/a_commands/at.html and https://pubs.opengroup.org/onlinepubs/9699919799/utilities/at.html
Other systems like SunOS or the BSDs also appear to use `-r` to remove a job.
at
To recreate the issue, use the following playbook:
```
- hosts: aix
gather_facts: no
tasks:
- at:
command: "ls -d / > /dev/null"
state: absent
```
This fails with:
```
fatal: [aix-host1]: FAILED! => {
"changed": false,
"cmd": …
```

at: add support for AIX

---

plugins/modules/sysctl.py
tests/integration/targets/sysctl/tasks/main.yml

the order of actions for setting, persisting and activation is changed,
to not persist an invalid sysctl value. This is only enforced when
sysct_set is True.
sysctl
we had some "fun" with the original behaviour in this PR: https://github.com/dev-sec/ansible-os-hardening/pull/312
Once a invalid value is persisted every change of a sysctl (with a reload) triggers an error. This complecates debugging and makes the real error non obvious for the user.
Playbook:
```yaml
- hosts: localhost
tasks:
- name: Set sysctl property using module
sysctl:
name: vm.mmap_rnd_bits
value: '1024'
state: present
reload: yes
sysctl_set: True
```
Before:
```
...
fatal: [localhost]: FAILED! => {
"changed": false,
"invocation": {
"module_args": {
"ignoreerrors": false,
"name": …
```

do not persist sysctl when value is invalid

---

changelogs/fragments/firewalld_zone_target.yml
plugins/modules/firewalld.py
tests/integration/targets/firewalld/tasks/run_all_tests.yml
tests/integration/targets/firewalld/tasks/zone_target_test_cases.yml

Bring back the `target` feature in the firewalld module.
The feature was left out when the firewalld module was moved from `community.general` to `ansible.posix`
Fixes #112
firewalld

firewalld: bring back zone target set

---

docs/ansible.posix.firewalld_module.rst
plugins/modules/firewalld.py
tests/integration/targets/firewalld/tasks/port_forward_test_cases.yml

Implement support in firewalld for use of the port forward API. Previously, the only way to forward ports using ansible was with the rich rule syntax. This change adds the `port_forward` parameter to manage port forwards directly.  The naming scheme for the parameter list is the same as existing firewalld naming. I opted to use a subgroup to clearly delineate the options and support better validation of the protocol parameter. 
Fixes: ansible-collections/ansible.posix#100
firewalld

firewalld: Add support for firewalld port forwarding

---

tests/utils/shippable/shippable.sh

`ansible-galaxy collection install` is currently failing, likely as the chown isn't present

AZP: Ensure collection dir is writable

---

changelogs/fragments/144_add_community_docker_connection_plugin_alias.yml
plugins/action/synchronize.py

The synchronize action plugin has a built-in list of connection plugins that it knows how to handle.
One of those connection plugins is the docker connection plugin. And because the docker content has been moved around quite a lot, the docker connection plugin has quite a few names:
- docker in Ansible 2.9,
- community.general.docker for community.general < 2.0.0, and
- community.docker.docker since a few months ago.
And while the synchronize module already knew about the first two names, the last one was still missing. This commit fixes that omission and adds a third name into the mix.
Fixes #132 
synchronize

Inform synchronize module about community.docker collection

---

plugins/action/synchronize.py

This fixes the old [bug #17492: "Do not prepend PWD when path is in form user@server:path or server:path"](https://github.com/ansible/ansible/issues/17492) (again).
Fix was already in the [ansible/ansible repo pull request 33998](https://github.com/ansible/ansible/pull/33998) as of December 2017, but never got merged.
There are several instances where the `_get_absolute_path` function is called. This should only happen for relative paths on a local file system and hence
* not for paths on a remote server
* nor for absolute paths.
The synchronize.py plugin checked before calling this function whether it was necessary to call `_get_absolute_path`.
It should not convert a path to an absolute path when it:
* contains a colon (path on remote server) or
* starts with a slash forward (absolute …

Bugfix for #17492 "Do not prepend PWD when path is in form user@server:path or server:path" 

---

plugins/modules/synchronize.py

Removed hard-coded ssh control path `"none"` to make sure `synchronize` module respects `ansible_ssh_common_args`. When users want to configure (disable/enable) connection multiplexing they can do so either in Ansible (`ansible.cfg`) or in their SSH config outside Ansible (`~/.ssh/config`). Either way the synchronize module should respect that and not override the ability to use connection multiplexing by setting the control path to `"none"`.
Fixes [bug #24365](https://github.com/ansible/ansible/issues/24365)
This is a new attempt to get rid off this long standing bug and now includes an option to allow or disable SSH connection multiplexing. For historic reasons the default is set to disable connection multiplexing, which ensures playbooks that rely on the old behavior of hard-coded …

Bugfix for #24365: "Added option to allow SSH connection multiplexing"

---

changelogs/fragments/156-fix_no-log-needed_false_positives.yml
plugins/modules/authorized_key.py
plugins/modules/mount.py

Ansible sanity test `validate-modules` triggers false-positives and hints `no-log-needed` errors for module parameters containing either `key` or `pass`in their names, as in:
```
2021-03-16 20:27:04.127992 | centos-8 | ERROR: Found 3 validate-modules issue(s) which need to be resolved:
2021-03-16 20:27:04.128105 | centos-8 | ERROR: plugins/modules/authorized_key.py:0:0: no-log-needed: Argument 'key' in argument_spec could be a secret, though doesn't have `no_log` set
2021-03-16 20:27:04.128204 | centos-8 | ERROR: plugins/modules/authorized_key.py:0:0: no-log-needed: Argument 'key_options' in argument_spec could be a secret, though doesn't have `no_log` set
2021-03-16 20:27:04.128303 | centos-8 | ERROR: plugins/modules/mount.py:0:0: no-log-needed: Argument 'passno' in argument_spec could …
```

add no_log=False to clear false-positives

---

changelogs/fragments/sanity_test_ignore_file.yml
tests/sanity/ignore-2.12.txt

Add ignore file(ignore-2.12.txt) to cover sanity test on the current devel version 2.12
- ansible-test
This fix will avoid the following errors during sanity test:
```
ERROR: Found 8 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/synchronize.py:0:0: doc-default-does-not-match-spec: Argument '_local_rsync_path' in argument_spec defines default as ('rsync') but documentation defines default as (None)
ERROR: plugins/modules/synchronize.py:0:0: doc-default-does-not-match-spec: Argument '_substitute_controller' in argument_spec defines default as (False) but documentation defines default as (None)
ERROR: plugins/modules/synchronize.py:0:0: nonexistent-parameter-documented: Argument 'use_ssh_args' is listed in …
```

Add ignore file for sanity test on devel version 2.12

---

changelogs/fragments/159-fix-60-deprecated-ansible_ssh_user.yml
plugins/action/synchronize.py
plugins/modules/synchronize.py
tests/unit/plugins/action/fixtures/synchronize/basic/taskvars_in.json
tests/unit/plugins/action/fixtures/synchronize/basic/taskvars_out.json
tests/unit/plugins/action/fixtures/synchronize/basic_become/task_vars_in.json
tests/unit/plugins/action/fixtures/synchronize/basic_become/task_vars_out.json
tests/unit/plugins/action/fixtures/synchronize/basic_become_cli/task_vars_in.json
tests/unit/plugins/action/fixtures/synchronize/basic_become_cli/task_vars_out.json
tests/unit/plugins/action/fixtures/synchronize/basic_vagrant/task_vars_in.json
tests/unit/plugins/action/fixtures/synchronize/basic_vagrant/task_vars_out.json
tests/unit/plugins/action/fixtures/synchronize/basic_vagrant_become_cli/task_vars_in.json
tests/unit/plugins/action/fixtures/synchronize/basic_vagrant_become_cli/task_vars_out.json
tests/unit/plugins/action/fixtures/synchronize/basic_vagrant_sudo/task_vars_in.json
tests/unit/plugins/action/fixtures/synchronize/basic_vagrant_sudo/task_vars_out.json
tests/unit/plugins/action/fixtures/synchronize/basic_with_private_key/taskvars_in.json
tests/unit/plugins/action/fixtures/synchronize/basic_with_private_key/taskvars_out.json
tests/unit/plugins/action/fixtures/synchronize/delegate_remote/task_vars_in.json
tests/unit/plugins/action/fixtures/synchronize/delegate_remote/task_vars_out.json
tests/unit/plugins/action/fixtures/synchronize/delegate_remote_play_context_private_key/task_vars_in.json
tests/unit/plugins/action/fixtures/synchronize/delegate_remote_play_context_private_key/task_vars_out.json
tests/unit/plugins/action/fixtures/synchronize/delegate_remote_su/task_vars_in.json
tests/unit/plugins/action/fixtures/synchronize/delegate_remote_su/task_vars_out.json
tests/unit/plugins/action/fixtures/synchronize/delegate_remote_with_private_key/task_vars_in.json
tests/unit/plugins/action/fixtures/synchronize/delegate_remote_with_private_key/task_vars_out.json

Documentation doesn't refer to `ansible_ssh_user` anymore, not even as a deprecated option: https://docs.ansible.com/ansible/2.9/user_guide/intro_inventory.html, although `synchronize`'s action plugin and unit tests still use it in place of (or mixed with) `ansible_user`.
Fixes #60 
This pull request turns all *ansible_ssh_user*, *ansible_ssh_port* and *ansible_ssh_host* into ***ansible_user***,  ***ansible_port*** and ***ansible_host***.
synchronize

Fix ansible_ssh_user

---

changelogs/fragments/134_authorized_key.yml
plugins/modules/authorized_key.py

Fixes: #134
changelogs/fragments/134_authorized_key.yml

authorized_key: Add support for additional key types

---

changelogs/fragments/185_mount_at_boot.yml
plugins/modules/mount.py

Fix `boot` option handling on Solaris correctly when it specified `false`(or `no`).
* Fixes #184
- ansible.posix.mount
None

[mount] Fix boot option handling on Solaris correctly

---

changelogs/fragments/167-synchronize-add_delay_option.yml
plugins/modules/synchronize.py

Fixes https://github.com/ansible-collections/ansible.posix/issues/157
synchronize
This does not disable the `delay-updates` by default, so current behaviour will not be changed, but adds an option which can be set to false and disable `delay-updates`.

synchronize: add delay_updates option

---

changelogs/fragments/synchronize.yml
plugins/modules/synchronize.py

synchronize: correct typo

---

changelogs/fragments/169_add_lineseparator_to_command.yml
plugins/modules/at.py

Fixes #169
- ansible.posix.at
This PR addresses the issue #169. In RHEL8 environment, the command line specified by the `command` parameter will not execute because line-saparater is not inserted at the end of command line.
For the RHEL7 environment(or others), an extra line separator will be insterted at the end of the command line, but I think it is unaffected for `at` command behavior.

Append line-separator to the end of command line

---

changelogs/fragments/196_boot_opt_for_linux.yml
plugins/modules/mount.py
tests/integration/targets/mount/tasks/main.yml

Rebased and recreate pull request based on #182.
* Fixes #28
* Modified behavior to set noauto option if boot is 'no' on Linux system
* Modified integration test to use filesize module instead of dd
- ansible.posix.mount
I created this new PR because I accidentally closed #182.

Modify boot option handling on Linux systems

---

changelogs/fragments/193_firewalld.yml
plugins/modules/firewalld.py

Timeout parameter takes value which is specified in seconds.
Fixes: #193

firewalld: Specify unit for timeout

---

changelogs/fragments/175_synchronize.yml
plugins/modules/synchronize.py

Docs should read ``--delete-after`` instead of ``--delete-excluded``.
Fixes: #175

synchronize: fix misc typo

---

changelogs/fragments/124_acl.yml
plugins/modules/acl.py

Added new alias ``recurse`` for parameter ``recursive``.
Fixes: #124
changelogs/fragments/124_acl.yml
plugins/modules/acl.py

acl: Add new alias

---

changelogs/fragments/204_csh_shell.yml
plugins/shell/csh.py

Fixes: #204
changelogs/fragments/204_csh_shell.yml
plugins/shell/csh.py

csh: Define ``ECHO`` and ``COMMAND_SEP``

---

changelogs/fragments/179_firewalld.yml
plugins/modules/firewalld.py
tests/integration/targets/firewalld/tasks/main.yml
tests/integration/targets/firewalld/tasks/port_forward_test_cases.yml
tests/integration/targets/firewalld/tasks/port_test_cases.yml
tests/integration/targets/firewalld/tasks/run_all_tests.yml

Use APIs like ``query*`` instead of ``get*``.
Fixes: #179
tests/integration/targets/firewalld/tasks/main.yml
tests/integration/targets/firewalld/tasks/port_forward_test_cases.yml
tests/integration/targets/firewalld/tasks/port_test_cases.yml
tests/integration/targets/firewalld/tasks/run_all_tests.yml

firewalld: Ensure idempotency

---

changelogs/fragments/203_boot_opt_for_bsd.yml
plugins/modules/mount.py

Modify boot option handling on FreeBSD, NetBSD and OpenBSD systems
* Fixes #28 for BSD systems
* Porting PR #196 to BSD systems
- plugins/modules/mount.py
Tested on the following platforms:
- FreeBSD 13.0
- NetBSD 9.1
- OpenBSD 6.9

Modify boot option handling on BSD systems

---

changelogs/fragments/187-fix-synchronize-become-user.yml
plugins/action/synchronize.py
tests/unit/plugins/action/fixtures/synchronize/basic_become/meta.yaml
tests/unit/plugins/action/fixtures/synchronize/basic_become_cli/meta.yaml

When `become_method` is sudo, the `synchronize` module ignores `become_user`, always running as root.  This means one cannot create files as a target user, when they need to get in via a third user and can only `sudo` via that one.  In my case, I'm connecting via a special provisioning user that has sudo privs, but I need to create the files as the `become_user`.  I'm using it to deposit skeleton files, and there should be no reason to run another task with `chown`; after all, the documentation already describes the desired behavior:
>  The user and permissions for the synchronize `dest` are those of the `remote_user` on the destination host or the `become_user` if `become=yes` is active.
This patch takes the running `become_user` (if it's not `None`) and adds it to the `sudo` command …

synchronize: fix to honor become_user when become_method sudo

---

changelogs/fragments/213_quote_cmd_args.yml
plugins/modules/synchronize.py
tests/integration/targets/synchronize/aliases

fix quoting for specific cmd arguments
Fixes:
- #24
- #190 
ISSUE TYPE:
COMPONENT NAME:
module: synchronize

synchronize: quotes around arguments

---

changelogs/fragments/215_fix_REJECT_target_name.yml
plugins/modules/firewalld.py
tests/integration/targets/firewalld/tasks/zone_target_test_cases.yml

Fix setting default target to reject. The target name is %%REJECT%% not REJECT.
https://firewalld.org/documentation/zone/options.html
After this pull request to way to set REJECT would be
```paste below
- name: "Set target to REJECT for public"
ansible.posix.firewalld:
zone: public
permanent: yes
target: '%%REJECT%%'
state: enabled
become: true
```
firewalld
This snippet would fail due to there not being target called REJECT and using %%REJECT%% is not in allowed values for target
```paste below
- name: "Set target to REJECT for public"
ansible.posix.firewalld:
zone: public
permanent: yes
target: 'REJECT'
state: enabled
become: true
```
Ansible error
```paste below
{
"msg": "ERROR: Exception caught: org.fedoraproject.FirewallD1.Exception: INVALID_TARGET: REJECT …
```

fix REJECT target name

---

changelogs/fragments/214-add_firewalld_info_module.yml
plugins/modules/firewalld_info.py
tests/integration/targets/firewalld_info/aliases
tests/integration/targets/firewalld_info/tasks/main.yml
tests/integration/targets/firewalld_info/tasks/run_tests_in_started.yml
tests/integration/targets/firewalld_info/tasks/run_tests_in_stopped.yml

Add new `firewalld_info` module to `ansible.posix` collection.
* Gathering information about `firewalld` zone settings
* fixes #98
- ansible.posix.firewalld_info
None

Add new firewalld_info module to ansible.posix collection

---

changelogs/fragments/229_add_podman_connection_plugin_to_synchronize.yml
plugins/action/synchronize.py

For fixing issues with molecule: https://github.com/ansible-community/molecule-podman/issues/45
synchronize
Add `podman` connections as it's done with buildah and docker.
```paste below
```

Allow podman connections in synchronize module

---

changelogs/fragments/firewalld_test.yml
tests/integration/targets/firewalld/aliases
tests/integration/targets/firewalld/tasks/main.yml
tests/integration/targets/firewalld/tasks/run_all_tests.yml
tests/integration/targets/setup_pkg_mgr/tasks/main.yml

tests/integration/targets/firewalld/aliases
tests/integration/targets/setup_pkg_mgr/tasks/main.yml

Enable firewalld tests

---

changelogs/fragments/230_complete_podman_support_for_synchronize.yml
plugins/action/synchronize.py

synchronize
```paste below
```
Continue of #229
For fixing https://github.com/ansible-community/molecule-podman/issues/45

Complete adding podman connection to synchronize

---

changelogs/fragments/226_sysctl_fix_integration_test.yml
tests/integration/targets/sysctl/tasks/main.yml

sysctl integration tests inside docker are being skipped as the check ansible_facts.virtualization_type == 'docker' fails. 
On Debugging, ansible_facts.virtualization_type is being returned as "container".
sysctl
Ansible Version 
- ansible [core 2.11.2] 
Docker Version 
- Docker version 20.10.7, build f0df350
OS
- Fedora 34
Actual Results
```
PLAY RECAP *********************************************************************
testhost                   : ok=1    changed=0    unreachable=0    failed=0    skipped=44   rescued=0    ignored=0   
```
Likely this code is related: https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/virtual/linux.py#L113

Fix: sysctl integration test - virtualization type

---

changelogs/fragments/241-synchronize-shell-quoting.yml
plugins/action/synchronize.py
plugins/modules/synchronize.py

The synchronize action plugin and module were a bit sloppy when it came to the command-line parameter quoting and that caused failure on some systems (for example, on Fedora 34).
This commit makes sure any arguments with potentially problematic characters are quoted before being used.
Fixes https://github.com/ansible-collections/ansible.posix/issues/242
synchronize

Properly quote Synchronize

---

changelogs/fragments/233-fix-wrong-firewalld-version-info.yml
plugins/modules/firewalld.py

Version of firewalled seems to be wrong. 3.0.9 version of that package does not exist.
The latest release of firewalled: https://github.com/firewalld/firewalld/releases
```

Fix requires firewalld version in comments for permanent parameter.

---

changelogs/fragments/222_synchronize.yml
plugins/action/synchronize.py
plugins/modules/synchronize.py

SSH configuration migrated from Ansible configuration to
SSH connection configuration. Make ``synchronize`` understand
this.
Fixes: #222
changelogs/fragments/222_synchronize.yml
plugins/action/synchronize.py

synchronize: Use SSH args from SSH connection plugins

---

changelogs/fragments/247_firewalld.yml
plugins/modules/firewalld.py
tests/integration/targets/firewalld/tasks/run_all_tests.yml

* Correct queryForwardPort API usage
* Enable port_foward_test_cases tests
Fixes: #247
tests/integration/targets/firewalld/tasks/run_all_tests.yml

firewalld: Correct usage of queryForwardPort

---

changelogs/fragments/254_variable_warnings.yml
plugins/modules/firewalld.py

Display warning message if the wrong parameter set to `masquerade` or `icmp-block-inversion`
* Fixes #249
It is a part of #249. Currently, the variable type of the above two parameters is `str`, but will be `changed` to bool in the future. As a starting point, this fix displays a warning message if a non-boolean value is specified.
- ansible.posix.firewalld
```
None
```

Display warning message for masquerade and icmp-block-inversion

---

changelogs/fragments/255_authorized_key_url.yml
plugins/modules/authorized_key.py

Add lookup.url example since using `split_lines=False` is not straight-forward.
ansible.posix.authorized_key

authorized_key: add lookup.url example

---

bindep.txt

This adds rsync to the bindep.txt file, which will ensure rsync is
installed as a dependency for execution environments.
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

Add bindep.txt file for execution environments

---

changelogs/fragments/263_profile_tasks_with_serial.yml
plugins/callback/profile_tasks.py

Correctly calculate task execution time with serial execution
- Fixes #83 
- ansible.posix.profile_tasks
After applying this PR, I can confirm that the task execution time with serial execution is correct:
- Test playbook:
```YAML
---
- hosts: issue_83
gather_facts: false
connection: local
serial: 1
tasks:
- name: TASK_A
shell: sleep 3
- name: TASK_B
shell: sleep 5
- name: TASK_C
shell: sleep 1
```
- Results:
```
$ ansible-playbook -i inventory playbook/profile_tasks/issue_83.yml 
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names 
to new standard, use callback_enabled instead. This feature will be removed 
from ansible-core in version 2.15. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.
PLAY …
```

profile_tasks - Correctly calculate task execution time with serial execution

---

changelogs/fragments/disable_selinux_via_kernel_cmdline.yml
plugins/modules/selinux.py
tests/integration/targets/selinux/tasks/selinux.yml

The ability to disable SELinux from userspace based on the configuration
file is being deprecated in favor of the selinux=0 kernel boot
parameter. (Note that this affects only the "full" disable; switching
to/from permissive mode will work the same as before.)
Therefore, enhance the selinux module to try to set/unset the kernel
command-line parameter using grubby when enabling/disabling SELinux.
If the grubby package is not present on the system, the module will only
update the config file and report a warning. Note that even with the
runtime disable functionality removed, setting SELINUX=disabled in the
config file will lead to a system with no SELinux policy loaded, which
will behave in a very similar way as if SELinux was fully disabled, only
there could still be some minor performance …

selinux: update kernel boot params when disabling/re-enabling SELinux

---

changelogs/fragments/211_fstab_append_newline.yml
plugins/modules/mount.py
tests/integration/targets/mount/tasks/main.yml

Modify mount module to add a newline at the end of line in `/etc/fstab`.
Fixes #210
- ansible.posix.mount
None

mount - add a newline at the end of line in fstab

---

changelogs/fragments/shell_escape_full_path_for_rsync.yml
plugins/modules/synchronize.py
tests/integration/targets/synchronize/tasks/main.yml

Any whitespace in path to playbook directory causes rsync to incorrectly chdir fail to correctly run.
Any whitespace in path to playbook directory causes rsync to incorrectly chdir fail to correctly run.
ansible.posix.synchronize
Example :
```
cd "/home/a/ansible plays"
task:
- synchronize:
src: a
dest: b
```
Results in the following error being thrown
```
fatal: [remote-host]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' /home/a/ansible plays/deployments// remote-user@remote-host:/b/", "msg": "rsync: [sender] link_stat \"/home/a/ansible\" failed: No such file or …
```

Whitespace in fully  path to playbook causes rsync to fail

---

.azure-pipelines/azure-pipelines.yml

Replace Fedora 33 with Fedora 35 for devel tests 
- Relates to https://github.com/ansible-collections/overview/issues/45#issuecomment-963553255
- azure-pipelines/azure-pipelines.yml
None

[CI] Replace Fedora 33 with Fedora 35 for devel tests 

---

changelogs/fragments/287_firewalld_requirements.yml
plugins/modules/firewalld.py

The firewalld module uses python-firewall to manage firewalld. However, it is often misunderstood by users as it is not listed in the requirements.
- Fixes #286
None

[docs] Add python-firewall to requirements of firewalld

---

changelogs/fragments/288_mounts_options.yml
plugins/modules/mount.py

This removes the `intr` option from the documentation example for nfs mounts.
mount.py
According to the nfs [manpage](https://linux.die.net/man/5/nfs) the `intr/ nointr` option has been deprecated with Kernel 2.6.25 which was released in April 2008 [wiki](https://en.wikipedia.org/wiki/Linux_kernel_version_history)
Even RHEL 6.10 which is already on Extended life cycle support is using a newer 2.6 Kernel. https://access.redhat.com/articles/3078
This does not change any module functionality. It simply removes the option from the nfs mount example.

Remove deprecated option from nfs mount example

---

changelogs/fragments/297_firewalld_exclusive_options_handling.yml
plugins/modules/firewalld.py
tests/integration/targets/firewalld/tasks/source_test_cases.yml

Refine the handling of exclusive options using `mutually_exclusive`:
- Fixes #255
- ansible.posix.firewalld
None

Refine the handling of exclusive options

---

changelogs/fragments/302_shippable_exit_code.yml
tests/utils/shippable/shippable.sh

Fix wrong exit code -1 in CI entrypoint to address shellcheck failure:
- Fixes #301
- tests/utils/shippable/shippable.sh
None

[CI] Fix exit code in CI entrypoint to address shellckeck issue

---

changelogs/fragments/299_seboolean_python3.yml
plugins/modules/seboolean.py

In modern systems (RHEL8+) with python3 default, the library requirement is `python3-libsemanage`.
Updated `libsemanage-python` to `python3-libsemanage`.
- Fixes `RHEL8 python3 support`
plugins/modules/seboolean.py
```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'semanage'
fatal: [demo.example.com]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (libsemanage-python) on demo.example.com's Python /usr/libexec/platform-python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on …
```

Add RHEL8 library python3-libsemanage

---

changelogs/fragments/304_pep632.yml
plugins/module_utils/_version.py
plugins/module_utils/firewalld.py
plugins/module_utils/version.py
plugins/modules/firewalld_info.py

Replace `distutils.*` with included module in ansible-core 2.12 to addresss PEP 632 if available. 
It does not change the behavior of ansible-core 2.11 or earlier.
- Fixes #303
- Addresses PEP 632(https://www.python.org/dev/peps/pep-0632/)
- plugins/module_utils/firewalld.py
- - plugins/modules/firewalld_info.py
None

Replace distutils with included module in ansible-core 2.12 to address PEP 632

---

.azure-pipelines/azure-pipelines.yml

Update AZP matrix to replace RHEL7.6 with RHEL7.9 for the following test environments:
- Remote 2.9
- Remote 2.10
Trying to address the following CI issue on RHEL7.6 test environment:
```
02:11 https://rhui3.us-east-1.aws.ce.redhat.com/pulp/content/rhui-client-config/rhel/server/7/x86_64/os/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
02:11 Trying other mirror.
02:11 To address this issue please refer to the below knowledge base article 
02:11 
02:11         compromise:
02:11 
02:11             yum-config-manager --save --setopt=rhui-REGION-client-config-server-7.skip_if_unavailable=true
02:11 
02:11 failure: repodata/repomd.xml from rhui-REGION-client-config-server-7: [Errno 256] No more mirrors to try.
02:11 …
```

Update AZP matrix to replace RHEL7.6 with 7.9

---

.azure-pipelines/azure-pipelines.yml

Remove CentOS8 test from the following docker container tests:
_Note: CentOS8 container test has already been removed from the devel branch test._
- 2.12
- 2.11
- 2.10
- 2.9
Reference: ansible-collections/news-for-maintainers#3
ansible.posix
None

[CI] Update AZP matrix to remove CentOS8 test

---

bindep.txt
shippable.yml

We are no longer using Shippable for CI tests, but it would be better to remove CentOS 8 tests from this just in case.
- shippable.yml
- bindep.txt
- Reference0: #321
- Reference1: https://github.com/ansible-collections/news-for-maintainers/issues/3

[CI] Update AZP matrix to remove CentOS8 shippable test

---

.azure-pipelines/azure-pipelines.yml
README.md
changelogs/fragments/347_add_branch_213.yml

As a part of the issue https://github.com/ansible-collections/ansible.posix/issues/345, it addresses CI tests for stable-2.13.
None

Add testing against ansible-core 2.13

---

changelogs/fragments/353_ci_fix_unittest_for_synchronize.yml
tests/unit/plugins/action/test_synchronize.py

Added check_mode attr to synchronize plugin unit test:
* Added check_mode attribute to TaskMock class in the unit test for
synchronize plugin
* Fixes #352
- ansible.posix.tests.unit

[CI] Added check_mode attr to synchronize plugin unit test

---

.azure-pipelines/azure-pipelines.yml

Refactoring AZP CI matrix:
* https://github.com/ansible-collections/news-for-maintainers/issues/17
* https://github.com/ansible-collections/ansible.posix/pull/368
None

[CI] Refactoring AZP CI matrix

---

.azure-pipelines/azure-pipelines.yml
changelogs/fragments/375_update_azp_container.yml

Addresses the following requirements:
- https://github.com/ansible-collections/news-for-maintainers/issues/18
However, ansible.posix needs to support Ansible Engine 2.9, so we will keep 2.9, 2.10, and 2.11 in the CI tests for now.
None

[CI] Bump AZP container version

---

.azure-pipelines/azure-pipelines.yml

Removing Fedora35 and FreeBSD12.3 from CI tests for devel branch(docker and remote).
- Related to ansible-collections/news-for-maintainers/issues/21

[CI] Update AZP matrix to remove Fedora35 and FreeBSD12.3 tests from devel

---

changelogs/fragments/386_follow_ci_testing_rules.yml
plugins/modules/authorized_key.py
plugins/modules/mount.py
tests/integration/targets/authorized_key/tasks/setup_steps.yml

Currently, ansible-test-sanity-docker-devel is set `non voting`, but we need to fix pylint check error in several modules.
- https://ansible.softwarefactory-project.io/zuul/build/fbd5ac593fe44fa7b3d77e5557de1607
None

[CI] Address pylint check check error in ansible-test-sanity-docker-devel test

---

changelogs/fragments/373_firewall_fix_missing_library_message.yml
plugins/module_utils/firewalld.py

adds 'exact' python used by module  and hostname to avoid confusion
firewalld

More complete missing lib msg

---

changelogs/fragments/401_document_module_default_values.yml
plugins/modules/acl.py
plugins/modules/rhel_rpm_ostree.py

Updates documented default value for the acl module's entity parameter to an empty string and rhel_rpm_ostree's name parameter to an empty array correctly matching the actual implementation in both cases. This should fix currently failing test cases in the devel and milestone branches of CI/CD.
ansible.posix.acl
ansible.posix.rhel_rpm_ostree
Display the current documentation for the acl module using `ansible-doc ansible.posix.acl` or rhel_rpm_ostree module using `ansible-doc ansible.posix.rhel_rpm_ostree`
Alternatively using ansible-test on devel/milestone branches of ansible, execute:
`ansible-test sanity --test validate-modules plugins/modules/`
```
Running sanity test "validate-modules"
ERROR: Found 2 validate-modules issue(s) which need to be resolved:
ERROR: …
```

Update documented default parameters to match implementation

---

changelogs/fragments/166_mount_absent_fstab.yml
plugins/modules/mount.py

Add absent_from_fstab option to remove the entry from fstab, but not unmount or delete the folder. Ideally this would have been the behavior of absent (as to mirror the behavior of present), but for backward compatibility I added a new verbose state
mount
Sometimes you may not want to delete the mountpoint (e.g. if it is not currently mounted and data is in the directory, the current behavior will simply error).

ansible.posix.mount: add absent_from_fstab option

---

changelogs/fragments/267_mount_ephemeral.yml
plugins/modules/mount.py
tests/integration/targets/mount/tasks/main.yml

Add `ephemeral` possible value for *state* parameter.
The `ephemeral` *state* allows end-users to mount a volume on a given path, without altering an *fstab* file or creating a dummy one.
There have been debates about splitting this module into an `fstab` module and a `mount` module, but nothing has been done in 5 years. This is why I'd like to propose this feature.
**Downside**: the way the `posix.mount` module handles mount options prevents it to be able to check exactly if the given *opts* perfectly match the mount options of an already mounted volume. To achieve this, the module would have to be aware of every `mount` default options, for all platforms. This is why `state=ephemeral` always return `changed=yes`.
In other terms, a `remount` will always be triggered if the volume is …

Add ephemeral state to mount fs without altering fstab

---

changelogs/fragments/407_fix_firewalld_port_test.yml
tests/integration/targets/firewalld/tasks/port_test_cases.yml

Modify firewalld port test cases to avoid port duplication behavior on RHEL9.x
- ansible.posix.firewalld
- None

Modify firewalld port test cases to avoid port duplication on RHEL9.x

---

changelogs/fragments/400-fix-boolean-values-in-docs.yml
plugins/modules/acl.py
plugins/modules/at.py
plugins/modules/authorized_key.py
plugins/modules/firewalld.py
plugins/modules/firewalld_info.py
plugins/modules/mount.py
plugins/modules/patch.py
plugins/modules/seboolean.py
plugins/modules/selinux.py
plugins/modules/synchronize.py
plugins/modules/sysctl.py

Fixes #397
Docs of several modules
Notes about testing. I'm not sure how to test collections properly. I have ran `ansible-test sanity --python 3.10` and `ansible-test units --python 3.10` in venv with `ansible-core 2.14` (with 0 return code in both cases). To run units test successfully I had to install `pytest-forked` pip package in addition to this one `pytest-xdist` from [test-requirements.txt](https://github.com/ansible-collections/ansible.posix/blob/main/test-requirements.txt#L2).
Note about issue #397. I haven't changed `yes` [here](https://github.com/ansible-collections/ansible.posix/blob/main/plugins/modules/mount.py#L97) because in this case it is value from `/etc/vfstab`. Also I've changed `yes` for parameters `masquerade` and `icmp_block_inversion` because …

Fix boolean values in docs

---

.azure-pipelines/azure-pipelines.yml
changelogs/fragments/409_update_azp_matrix.yml

To update AZP CI matrix for ansible-core devel branch to address the following issue:
- Fixes #408 
- Update Fedora36 with 37
- Update RHEL8.6 with 8.7
- Update RHEL9.0 with 9.1
- Update FreeBSD 12.3 with 12.4
- Reference:  [ansible-test - new and deprecated platforms for testing #31 ](https://github.com/ansible-collections/news-for-maintainers/issues/31)

[CI] Update AZP CI matrix

---

changelogs/fragments/413-synchronize-seealso.yml
plugins/modules/synchronize.py

Module references must always have FQCN.
synchronize

Fix broken seealso in synchronize module

---

changelogs/fragments/399_firewalld_create_remove_zone_when_offline.yml
plugins/modules/firewalld.py
tests/integration/targets/firewalld/tasks/run_all_tests.yml
tests/integration/targets/firewalld/tasks/zone_test_cases.yml

Fixes #398 by checking the flag self.fw_offline and calling the offline specific APIs when the flag is true.
When attempting to add or remove zones, the ansible.posix.firewalld module would always call APIs as if it was online.
Specifically, the ZoneTransaction class assumed that self.fw  was a [FirewallClient](https://github.com/firewalld/firewalld/blob/e1407b44abc1618165accca2744226e3f0f74627/src/firewall/client.py#L2835), but when the daemon is offline, it is instead either a [Firewall](https://github.com/firewalld/firewalld/blob/e1407b44abc1618165accca2744226e3f0f74627/src/firewall/core/fw.py#L70) or [Firewall_test](https://github.com/firewalld/firewalld/blob/44200d0f508a990c5dfff9f480a6206ec507e229/src/firewall/core/fw_test.py#L55) based …

Updat ZoneTransaction to support operations when firewalld is offline

---

changelogs/fragments/419-fix-patch-doc.yml
docs/ansible.posix.patch_module.rst
plugins/modules/patch.py

Fixed lacking of `C()` for description of src option. And fixed by collection_prep.
Based on [this](https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#linking-and-other-format-macros-within-module-documentation) and [this discussion](https://github.com/ansible-community/community-topics/issues/116).
- `ansible.posix.patch` module 
```paste below
N/A
```

patch: fix documentation syntax

---

changelogs/fragments/426-firewalld_info-doc-update.yml
plugins/modules/firewalld_info.py

There was a typo in the docs of `firewalld_info`. Furthermore I slightly improved the examples by showcasing how to use the data gathered by this module. 
firewalld_info
I'm not sure whether I should also update the file `docs/ansible.posix.firewalld_info_module.rst` but I suspect it will be generated automatically?

firewalld_info: fixed typo in default_zone and improved examples

---

bindep.txt

Adds support for installing rsync for centos and related EL variants (AlmaLinux, Rocky, Oracle, etc)
rsync is an extremely common package, available in the base repos of all EL distros.
This is necessary to properly support [AWX-EE](https://github.com/ansible/awx-ee) and other community-built EL Execution Environments.
See: https://github.com/ansible/awx-ee/issues/167

bindep - install rsync on all EL variants

---

changelogs/fragments/402_firewall_fix_offline_interface_add.yml
plugins/modules/firewalld.py
tests/integration/targets/firewalld/tasks/interface_test_cases.yml
tests/integration/targets/firewalld/tasks/run_all_tests.yml

Fixes issue #357
The existing implementation had several issues which have been resolved by this PR:
- incorrectly assumed some zone always exists that contains the interface
- incorrectly included the logic to add the interface to the target zone inside of the condition checking if the interface is already assigned to a different zone (and needs to be removed)
- passed an invalid argument to the constructor for FirewallClientZoneSettings
```
- name: Add lo interface to trusted zone
ansible.posix.firewalld:
interface: lo
zone: trusted
permanent: Yes
state: enabled
```
```
TASK [firewalld : Add lo interface to trusted zone] ****************************
task path: /root/ansible_collections/ansible/posix/tests/output/.tmp/integration/firewalld-gpg …
```

Fix adding interface to zone when firewalld is offline

---

changelogs/fragments/404_firewalld_masquerade_icmp_block_inversion_bugfixes.yml
plugins/modules/firewalld.py
tests/integration/targets/firewalld/tasks/icmp_block_inversion_test_cases.yml
tests/integration/targets/firewalld/tasks/masquerade_test_cases.yml
tests/integration/targets/firewalld/tasks/run_all_tests.yml

Fixes #235
Fixes #116
The masquerade and icmp_block_inversion parameters are currently strings and the values are completely ignored by the module.  A warning was previously added that these values will be converted to a boolean in the future.
This PR updates the behavior so that when a boolean like value is provided, the value is correctly considered. If a boolean like string is **NOT** provided, the current behavior is retained and the value is treated as true.  Additionally, comprehensive tests are added for every combination of the parameters `state` _(enabled/disabled)_ and `icmp_block_inversion` / `masquerade` _(True/False/non-boolean string)_.
Given icmp block inversion is currently enabled
```
- name: Testing disable icmp block …
```

Bugfix masquerade icmp block inversion

---

changelogs/fragments/440-json-add-path-field.yaml
plugins/callback/json.py
plugins/callback/jsonl.py

Add the play and task path info (i.e., filename and line number) to the JSON that is emitted from the `json` and `jsonl` callback plugins, allowing more accurate post-mortem analysis.
Add the play and task path info (i.e., filename and line number) to the JSON that is emitted from the `json` and `jsonl` callback plugins, allowing more accurate post-mortem analysis.
- ansible.posix.json
- ansible.posix.jsonl
By also including the file/line number in the JSON data emitted, post-mortem analysis can unambiguously tie play/task log data to the specific play / task that generated it.  Without this information, it could be difficult for automated processes to precisely map log output back to the task that generated it (especially with playbooks that either do not name …

json[l] callback: add play/task path info

---

changelogs/fragments/441-json-add-indent-parameter.yaml
plugins/callback/json.py
plugins/callback/jsonl.py

Add `ANSIBLE_JSON_INDENT` parameter to both the `json` and `jsonl` callback plugins.  The default values are different between the two modules to maintain their existing behavior:
* json: indent==4, causing a prettyprint output
* jsonl: indent==0, causing a 1-line output
- ansible.posix.json
- ansible.posix.jsonl
One specific use-case that is enabled by this feature: if a user chooses to use the `jsonl` plugin so that they still get output at the end of each task (vs. only at the end of the play), they may also want human-readable output so that they can monitor the status of their play.  For example, setting the `jsonl` indent level to 4 gives a) output at the end of each task, and b) making that output be both machine readable and human readable.
Using this …

json[l] callback: add parameter to set JSON prettyprint indent level

---

changelogs/fragments/451_firewall_fix_protocol_parameter.yml
plugins/modules/firewalld.py

This PR resolves an issue where opening a port (e.g. `25/tcp`) resulted in opening all ports for the specified protocol (e.g. `tcp`)
Fixes https://github.com/ansible-collections/ansible.posix/issues/451
Many thanks to @nerrehmit and every one else who helped troubleshooting this!

fix firewalld protocol

---

changelogs/fragments/456_sysctl_fix_nonetype.yml
tests/integration/targets/sysctl/tasks/main.yml

Previously NoneType was allowable, now it fails to convert to a str type.
fix sysctl integration test failing on newer versions of core
Previously NoneType was allowable, now it fails to convert to a str
type.
sysctl

fix sysctl integration test failing on newer versions of core

---

changelogs/fragments/466-tests.yml
tests/integration/targets/acl/tasks/main.yml
tests/integration/targets/seboolean/tasks/main.yml
tests/integration/targets/selinux/tasks/main.yml

`include:` is removed for ansible-core 2.16 and no longer works with current devel.
- Test Pull Request
integration tests

Fix CI: replace `include:` with `include_tasks:`

---

.azure-pipelines/azure-pipelines.yml

Removes CI tests for FreeBSD 12.2 that are failing when trying to bootstrap http://pkg.freebsd.org/FreeBSD:12:amd64/release_2
Example PR affected https://github.com/ansible-collections/ansible.posix/pull/466
.azure-pipelines/azure-pipelines.yml
N/A

Fix CI: Remove FreeBSD 12.2 targets

---

.azure-pipelines/azure-pipelines.yml
changelogs/fragments/487_ci_update.yml

Drop OSX-10.11 and FreeBSD12.4 from CI
- Fixes #476
- Fixes #486
- Drop OSX10.11 from ansible:2.9 and ansible-core:2.10
- Drop FreeBSD12.4 from ansible-core:devel
None

Drop OSX10.11 and FreeBSD12.4 from CI

---

.azure-pipelines/azure-pipelines.yml
changelogs/fragments/508_ci_update.yml

Refactored CI tests:
* Remove tests for Ansible Core 2.10 and 2.11 that already reached EOL.
* Remote test target of ansible.posix will be the latest version of RHEL8,9 only.
* The target OS of container tests has been modified, and a few OS have been removed
* Add Ansible Core 2.16 and new devel branch to container and remote test target.
* https://github.com/ansible-collections/ansible.posix/issues/506
For CI testing, other platforms can be added as needed.
None

[CI] Refactoring CI tests for both remote and container tests

---

.azure-pipelines/azure-pipelines.yml
changelogs/fragments/510_ci_update.yml

Replace Fedora 38 container test with 39 for devel branch.
- Fixed /#509
- CI test Pull Request
None

[CI] Replace Fedora 38 with 39 for devel branch container test

---

changelogs/fragments/460-respawn.yaml
plugins/module_utils/_respawn.py
plugins/module_utils/firewalld.py
plugins/modules/firewalld_info.py
plugins/modules/seboolean.py
plugins/modules/selinux.py
tests/integration/targets/firewalld/tasks/main.yml

The seboolean, selinux, firewalld, and firewalld_info modules depend on
system bindings that are only available for the default system python
interpreter. ansible-core is not packaged for the default system python
interpreter on RHEL 8 and 9. When automatic interpreter discovery does
not occur (e.g. when using implicit localhost [1]), ansible-core will
not use the system interpreter to run ansible modules and the
aforementioned modules will not work even if the bindings are installed.
The RHEL ansible-core maintainers as well as the EPEL ansible and
ansible-collection-* package maintainers (inc. me) have gotten multiple
bug reports about this. We have been telling people to fix their setup
to use the correct Python interpreter. Fortunately, ansible-core 2.11
and above have a module …

Respawn modules to use the system python interpreter

---

changelogs/fragments/484-firewalld-offline.yml
plugins/modules/firewalld.py
tests/integration/targets/firewalld/tasks/service_test_cases.yml

`ansible.posix.firewalld` has an `offline` flag, but it currently does not do anything. What most people expect it to do is allow the task to proceed even when `firewalld` is offline, so it makes the most sense for it to override the `immediate` flag and prevent the module from throwing an error in that case.
Fixes #81.
firewalld

firewalld: make offline do something

---

.azure-pipelines/azure-pipelines.yml

Current CI fails due to the  release_1/ dir returning 404, this will move to working release_2/ dir
CI

update ci target for freebsd 13, r1 is eol

---

.azure-pipelines/azure-pipelines.yml
tests/utils/shippable/shippable.sh

- Sanity tests fail; remove problematic Shippable-specific parts of shippable.sh script.
- FreeBSD 12.4 have apparently been removed also from older versions of ansible-test.
- Test Pull Request
CI

Fix CI issues

---

plugins/modules/mount.py

I have modified warning conditions when using opts parameter with `noauto` value. Now it doesn't give unnecessary warning when user doesn't have used boot parameter. It will now check that if boot parameter is true and opts parameter has `noauto`. One alternative is to check if boot is defined instead. But in case boot is false there is no need to give warning because noauto is same as boot false.
Fixes #522
mount
```paste below
```

mount: edit boot parameters warning condition

---

changelogs/fragments/504-firewalld_info-warning.yaml
plugins/modules/firewalld_info.py

When using the `ansible.posix.firewalld_info` module with given `zones:` a warning about ignored zones is thrown, even no zones were ignored
task
```yaml
- name: fetch current info about zone '{{ fw_zone.name }}'
ansible.posix.firewalld_info:
zones:
- '{{ fw_zone.name }}'
register: fw_zone_info
```
output
```
[...]
TASK [firewalld : fetch current info about zone 'public'] *********************************************************************************************************
[WARNING]: Please note: zone:() have been ignored in the gathering process.
[...]
```
With this change, the warning is only shown, when zones were ignored.
firewalld_info
```paste below
```

Warn only when zones were ignored in firewalld_info

---

changelogs/fragments/496_seboolean-make-it-wrk-with-SELinux-disabled.yaml
plugins/modules/seboolean.py

Sometimes it's necessary to configure SELinux before it's enabled on the system. There's `ignore_selinux_state` which should allow it. Before this change `seboolean` module failed on SELinux disabled system even with `ignore_selinux_state: true` and SELinux policy installed while `semanage boolean` worked as expected:
$ ansible -i 192.168.121.153, -m seboolean -a "name=ssh_sysadm_login state=on ignore_selinux_state=true" all
192.168.121.153 | FAILED! => {
"ansible_facts": {
"discovered_interpreter_python": "/usr/bin/python3"
},
"changed": false,
"msg": "Failed to get list of boolean names"
}
$ ssh root@192.168.121.153 semanage boolean -l | grep ssh_sysadm_login
ssh_sysadm_login               (off  ,  off)  Allow ssh to sysadm login
It's caused by `selinux.security_get_boolean_names()` and …

seboolean: make it work with disabled SELinux

---

tests/integration/targets/selinux/tasks/selogin.yml

Some integration test tasks used the old FQCNs of commuinity.general.
This PR will replace old FQCN(community.general.system.selogin)with new cummonity.general.selogin
- ansible.posix.selinux
None

[CI] Replaced old selogin FQCN for integration tests

---

.azure-pipelines/azure-pipelines.yml

The devel version of ansible-test has been updated to include support for FreeBSD 13.3, so this change swaps out 13.2 accordingly.
See https://github.com/ansible-collections/news-for-maintainers/issues/67

ci: replace freebsd 13.2 with 13.3

---

changelogs/fragments/490_doc_authorized_key_path.yml
plugins/modules/authorized_key.py

Docs: Fixed unclearance in documentation connected wirh relative path
Added additional description in documentation.
authorized_key.py
Clarify the documentation unclearance in connected with relative path `~/.ssh/authorized_keys`
The purpose of the pull request is to eliminate ambiguities in the documentation.
In our case, when using the ~ sign, we get the user's root directory (although we explicitly specify a different username)
Here is the issue and full picture of problem which we want to fix: [LINK](https://github.com/ansible-collections/ansible.posix/issues/483)
Closese:  #483

Docs/authorized_key: clarify that the path key should probably NOT be set

---

.ansible-lint
.azure-pipelines/azure-pipelines.yml
tests/sanity/ignore-2.18.txt

ansible-lint makes the nightly CI fail (https://dev.azure.com/ansible/ansible.posix/_build/results?buildId=114105&view=logs&j=2671e6a6-f41a-533c-2720-8ffdcf8ab96f&t=5b604a49-baaa-558f-6ab2-4a2ff646af4f) due to two rules:
- `meta-runtime[unsupported-version]`: it doesn't like that the collection supports ansible-core versions that are EOL. This rule simply doesn't make any sense, and it should be disabled by default IMO.
- `fqcn[deep]`: this rule produces false positives for files in `tests/unit/plugins/action/fixtures/`.
Also adds sanity ignore file for ansible-core 2.18 (the version used by the current `devel` branch).
- Test Pull Request
ansible-lint in CI

Add basic ansible-lint config to fix CI; add ansible-core 2.17 to CI

---

.azure-pipelines/azure-pipelines.yml

Replace AZP container image version with 6.0.0:
- Fixes https://github.com/ansible-collections/ansible.posix/issues/549
See https://github.com/ansible-collections/news-for-maintainers/issues/71

[CI] Bump Azure test container to 6.0.0

---

README.md
changelogs/fragments/562_update_core_version.yml
meta/runtime.yml

Drop ansible-core 2.14 and set 2.15 minimum version.
```paste below
N/A
```

Drop ansible-core 2.14 and set 2.15 minimum version

---

changelogs/fragments/548_add_foward.yml
plugins/modules/firewalld.py
tests/integration/targets/firewalld/tasks/source_test_cases.yml
tests/integration/targets/firewalld/tasks/zone_test_cases.yml

Adds firewalld functionality to do the equivalent of `firewall-cmd --add-forwarding --zone={zone}`.
Functionality is exactly analogous to the `firewall-cmd --add-masquerade --zone={zone}` already present.
Fixes #529
firewalld
Usage:
```
- ansible.posix.firewalld:
forward: true
state: enabled
permanent: true
zone: internal
```

Firewalld: Add functionality to set forwarding

---

changelogs/fragments/563_add_no_log_option.yml
plugins/modules/mount.py
tests/integration/targets/mount/tasks/main.yml

Allows you to set no_log on just the opts parameter.
This is useful for CIFS/SMB mounts that would otherwise leak secrets.
Adds feature from issue: . #497 
mount

(feat) add no_log option for 'opts' parameter

---

changelogs/fragments/567_remove_version_added.yml
plugins/modules/mount.py

Remove the wrong version_added section from the mount module. It's not the collection version; it should be the ansible-core version.
ansible.posix.mount
```paste below
None
```

Remove wrong version_added section from mount module

---

changelogs/fragments/570_nfs4_acl.yml
plugins/modules/acl.py

Fixed to set ACLs on paths mounted with NFSv4 correctly.
* Fixed #240
ansible.posix.acl
```paste below
None
```

Fixed to set ACLs on paths mounted with NFSv4 correctly

---

.azure-pipelines/azure-pipelines.yml
README.md
changelogs/fragments/571_ci_bump_core_version.yml
tests/sanity/ignore-2.19.txt

* bump devel test to ansible-core 2.19
* add ansible-core 2.18 to the stable list (CI only covers sanity tests at the moment)
ansible.posix
```paste below
None
```

[CI] bump ansible-core version to 2.19 for devel branch

---

changelogs/fragments/568_update_authorized_key.yml
plugins/modules/authorized_key.py
tests/integration/targets/authorized_key/defaults/main.yml
tests/integration/targets/authorized_key/tasks/check_path.yml
tests/integration/targets/authorized_key/tasks/main.yml

Add option to specify an absolute path to file with SSH key(s) for `authorized_key`
- `authorized_key`
Before this change you would need to get key using `ansible.builtin.slurp` or something like `ansible.builtin.command: cat <file>` with `register`
I tried to keep it as simple as possible
```paste below
- name: Set authorized keys taken from path
ansible.posix.authorized_key:
user: charlie
state: present
key: /home/charlie/.ssh/id_rsa.pub
```

authorized_key: Allow local path to a key

---

changelogs/fragments/387_callback_output_header.yml
plugins/callback/profile_roles.py
plugins/callback/profile_tasks.py
plugins/callback/timer.py

All three callback plugins (timer, roles, tasks) do not produce headers in the output that align with how we do "PLAY RECAP *********" that is generated by the "default" output callback. So these changes are provided to align the callback plugins and have a clean output that is much more readable.
Note, the asterisks are generated just as how they are for "PLAY RECAP", where it extends to the end of the terminal window.
I am considering this as a "bug" in that the output was never aligned, instead of a feature since this does not provide any new feature per-se. 
ansible.posix.timer
ansible.posix.profile_tasks
ansible.posix.profile_roles
The new output is shown below. You can see the headers are now all the same and broken down by PLAY, ROLE, TASKS, and PLAYBOOK …

Fix callback output to align header with roles, tasks and play RECAP

---

changelogs/fragments/365-boot-linux.yml
plugins/modules/mount.py
tests/integration/targets/mount/tasks/main.yml

There is no need for an exception on `defaults` option when adding `noauto`. Mount is implemented as last win.
from mount(8):
```
If you want to override mount options from /etc/fstab, you have to use the -o option:
mount device|dir -o options
and then the mount options from the command line will be appended to the list of options from /etc/fstab. This default behaviour can be changed using the --options-mode command-line option. The usual behavior is that the last
option wins if there are conflicting ones.
```
Fixes #364
- ansible.posix.mount
```paste below
```

mount: remove boot exception if defaults in opts

---

changelogs/fragments/580_drop_ansible214.yml
meta/runtime.yml
tests/integration/targets/selinux/tasks/selinux.yml

1. Drop ansible-core 2.14 and set 2.15 minimum version.
2. Modify conditions for selinux integration tests to avoid RHEL7.9 integration test failure.
- backports #562
- fixes #578
- ansible.posix(stable-1)
None

[backport][stable-1] Drop ansible-core 2.14 and set 2.15 minimum version

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/580_drop_ansible214.yml
galaxy.yml

Release 1.6.2 commit. The purpose of this release is to fix the version information that was reverted in 1.6.1.
It will replace the minimum version of Ansible Core 2.14 with 2.15.
* #149 
* ansible.posix(stable-1)
```paste below
None
```

Release 1.6.2 commit

---

.azure-pipelines/azure-pipelines.yml
changelogs/fragments/593_replace_freebsd_version.yml

Replace FreeBSD 13.3 with 13.4 and add FreeBSD 14.1 for integration test environments for ansible-core devel branch.
```paste below
None
```

Replace FreeBSD 13.3 with 13.4 and add FreeBSD 14.1 for devel

---

changelogs/fragments/597_remove_fstab_comment_on_updating.yml
plugins/modules/mount.py

 Remove comment from fstab entry on updating.

---

plugins/modules/sysctl.py

FreeBSD's [/boot/loader.conf](https://man.freebsd.org/cgi/man.cgi?loader.conf) may contain both `rc` and `sysctl`-like entries.
When I tried to edit this file with Ansible's `sysrc` module, I found out that it [does not support](https://docs.ansible.com/ansible/latest/collections/community/general/sysrc_module.html#notes) dot-separated keys. Searching the Internet wasn't helpful, but eventually, I realised I could modify the file with the `sysctl` module.
I think the existing example with `/tmp/test_sysctl.conf` is a bit contrived, so replacing it with `/boot/loader.conf` will make a real-world use case, and make it searchable on the Internet for others who run into the same issue as I did. It will also make it more consistent with the sysrc …

sysctl: Update custom sysctl file example

---

changelogs/fragments/626_profile_tasks_datetime_format.yml
plugins/callback/profile_tasks.py

The new `datetime_format` key will offer the possibility of providing a different date/time format than the default one (`'%A %d %B %Y  %H:%M:%S %z'`).
- The `iso8601` value can be used as an `'%Y-%m-%dT%H:%M:%S.%f'` alias (format of the ISO 8601 date/time standard).
The code has changed from using the `time` API to the `datetime` one in order to support sub-second precision (needed by the ISO 8601 format, for example).
Fixes: #279
plugins/callback/profile_tasks.py
- Output with no key which keeps current behavior:
```paste below
TASK [Import subscription manifest] ************************************************************************************************************************************************************************************************************* …
```

plugins/callback/profile_tasks.py: Add option to provide a different date/time format

---

.azure-pipelines/azure-pipelines.yml

CI seems to be failing for a month, reason is that freebsd 13.2 is no longer valid.
See https://github.com/ansible-collections/community.general/pull/8607
CI

Remove EOL FreeBSD 13.2 from CI

---

changelogs/fragments/650-profile_tasks_roles.yml
plugins/callback/profile_roles.py
plugins/callback/profile_tasks.py

The profile_roles and profile_tasks callbacks define methods `playbook_on_setup` and `playbook_on_stats` which have been deleted/deprecated:
- `playbook_on_stats` has been deprecated, `v2_playbook_on_stats` should be used instead (that one has already been there for many years: https://github.com/ansible/ansible/commit/ba0e5323d6feca04b721ae164e69b68bc1e97b92 was added in 2015).
- `playbook_on_setup` has been deleted (https://github.com/ansible/ansible/commit/eec57ec3965a6887c737e8b629e853ccf295d3ec), and its v2 variant was already deleted in 2017: https://github.com/ansible/ansible/commit/59d5481abb91c4d3b0bb96b8e8e592bb1dc3d234
Ref: #635
profile_roles
profile_tasks

profile_* callbacks: avoid deprecated/deleted functions

---

.azure-pipelines/azure-pipelines.yml
changelogs/fragments/655_ci_remove_devel_from_stable1.yml

Removed devel tests from CI matrix in stable-1. It only covers up to Ansible Core 2.18
- CI
```
None
```

[CI][stable-1] AZP remove ansible-core devel version tests from CI matrix in stable-1

---

.azure-pipelines/azure-pipelines.yml
README.md
changelogs/fragments/673_update_ci_20250805.yml
meta/runtime.yml

This PR is a backport pull request for #673 to stable-2:
- Addresses #672
- Bump test container version 7.0.0
- Removes Ansible Core 2.15 tests. Python 3.11 is no longer supported in Container 7.0.0.
None

[Backport][stable-2][AZP] #673
